### ISSUE TITLE
[Feature]: Add sensible defaults when not using issuer-uri

### ISSUE THREAD

**Issue by jnodorp-jaconi** [jaconi-io/morp#67]
### Prerequisites

- [X] I am running the most recent stable version.
- [X] I checked the documentation and found no answer.
- [X] I checked to make sure that this feature request has not already been filed.

### Problem Statement

When using a custom provider configuration (**not** using `Morp.oauth2-client.provider.*.issuer-uri`), there are no defaults configured for values that should have defaults:

- `userNameAttribute`

The problem propagates to registrations for that provider. Defaults are lacking for:

- `authorization-grant-type`
- `redirect-uri`

Additionally, there are some validation issues for lacking `client-secret`, even if overrides per tenant exist.

### Desired Solution

- `userNameAttribute ` should default to `sub`
- `authorization-grant-type ` should default to `authorization_code`
- `redirect-uri` should default to `"{baseUrl}/login/oauth2/code/{registrationId}"`
- `client-secret` should not fail validation if provided per tenant

### Alternatives

Alternatively all values can be provided manually. `client-secret` can be set to `~`.

### Context

Example config:
```yaml
morp:
  tenant:
    foo:
      registration:
        client-secret: secret
    bar:
      registration:
        client-secret: another-secret

  oauth2-client:
    registration:
      my-provider:
        client-id: morp
        # This should be the default!
        # authorization-grant-type: authorization_code
        # This should not complain when null but overridden by tenant.
        # client-secret: ~
        # This should be the default!
        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
    provider:
      my-provider:
        # This should be the default!
        # userNameAttribute: sub

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
