### ISSUE TITLE
[Feature]: Support missing `openid` scope

### ISSUE THREAD

**Issue by gschlueter-jaconi** [jaconi-io/morp#83]
### Prerequisites

- [X] I am running the most recent stable version.
- [X] I checked the documentation and found no answer.
- [X] I checked to make sure that this feature request has not already been filed.

### Problem Statement

When configuring an OAuth2 client registration without the `openid` scope:
```
      keycloak:
        client-id: morp
        scope:
          - profile
          - email
```

The OAuth2  authentication works, but an `Access denied` error is eventually returned, since the necessary `ROLE_PROXY` authority is never granted.

### Desired Solution

Implement the same logic to grant the `ROLE_PROXY` authority for plain OAuth2 clients (including claim validation).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
